language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

sudo: false

env:
  global:
    - DEFAULT=1
    - PHPCS=1

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: CODECOVERAGE=1
    - php: 7.1
      env: PHPCS=1
    - php: 7.1
      env: DEFAULT=0
    - php: 5.6
      env: PREFER_LOWEST=1

install:
  - composer self-update
  - sh -c "if [ '$PREFER_LOWEST' != '1' ]; then composer install --prefer-dist --no-interaction; fi"
  - sh -c "if [ '$PREFER_LOWEST' = '1' ]; then composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi"

before_script:
  - phpenv rehash
  - set +H

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then ./vendor/bin/phpunit; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then ./vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi"
  - sh -c "if [ '$CODECOVERAGE' = '1' ]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=clover.xml || true; fi"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
